import type {
  AlphaSignal,
  Asset,
  Event,
  FlowRecord,
  KOL,
  Project,
  PropagationLink,
  PropagationNode,
  Sentiment,
  TickerItem,
} from "./types";

// Deterministic pseudo-random spark generator (no hydration mismatch)
function spark(seed: number, len = 24, base = 100, vol = 0.04): number[] {
  const out: number[] = [];
  let v = base;
  let s = seed;
  for (let i = 0; i < len; i++) {
    s = (s * 9301 + 49297) % 233280;
    const r = s / 233280;
    v = v * (1 + (r - 0.5) * vol * 2 + 0.0015);
    out.push(Number(v.toFixed(2)));
  }
  return out;
}

const now = Date.now();
const H = 3600_000;
const D = 24 * H;

export const assets: Asset[] = [
  { symbol: "BTC", name: "Bitcoin", price: 96840, change24h: 2.34, marketCap: 1910e9, volume24h: 48.2e9, spark: spark(11, 32, 100, 0.025) },
  { symbol: "ETH", name: "Ethereum", price: 3624, change24h: 4.12, marketCap: 436e9, volume24h: 22.1e9, spark: spark(22, 32, 100, 0.03) },
  { symbol: "SOL", name: "Solana", price: 218.4, change24h: -1.82, marketCap: 103e9, volume24h: 4.8e9, spark: spark(33, 32, 100, 0.04) },
  { symbol: "HYPE", name: "Hyperliquid", price: 41.6, change24h: 12.7, marketCap: 13.8e9, volume24h: 1.2e9, spark: spark(44, 32, 100, 0.06) },
  { symbol: "PUMP", name: "Pump.fun", price: 0.082, change24h: -6.4, marketCap: 0.62e9, volume24h: 0.31e9, spark: spark(55, 32, 100, 0.07) },
  { symbol: "ONDO", name: "Ondo Finance", price: 1.94, change24h: 8.9, marketCap: 2.7e9, volume24h: 0.42e9, spark: spark(66, 32, 100, 0.05) },
  { symbol: "LINK", name: "Chainlink", price: 24.1, change24h: 3.3, marketCap: 15.6e9, volume24h: 0.9e9, spark: spark(77, 32, 100, 0.035) },
  { symbol: "AAVE", name: "Aave", price: 348, change24h: 5.6, marketCap: 5.2e9, volume24h: 0.34e9, spark: spark(88, 32, 100, 0.04) },
];

export const ticker: TickerItem[] = [
  { symbol: "BTC", price: 96840, change: 2.34 },
  { symbol: "ETH", price: 3624, change: 4.12 },
  { symbol: "SOL", price: 218.4, change: -1.82 },
  { symbol: "BNB", price: 712.5, change: 0.86 },
  { symbol: "XRP", price: 2.41, change: 6.7 },
  { symbol: "HYPE", price: 41.6, change: 12.7 },
  { symbol: "DOGE", price: 0.381, change: -2.1 },
  { symbol: "ONDO", price: 1.94, change: 8.9 },
  { symbol: "LINK", price: 24.1, change: 3.3 },
  { symbol: "AAVE", price: 348, change: 5.6 },
  { symbol: "AVAX", price: 41.2, change: -0.9 },
  { symbol: "SUI", price: 4.18, change: 7.2 },
  { symbol: "TIA", price: 6.04, change: -3.4 },
  { symbol: "ENA", price: 1.12, change: 11.3 },
  { symbol: "PEPE", price: 0.0000218, change: -4.6 },
  { symbol: "WIF", price: 2.74, change: 9.1 },
];

export const alphaSignals: AlphaSignal[] = [
  {
    id: "sig-1",
    title: "高可信KOL共振看多 ETH",
    direction: "bullish",
    confidence: 87,
    strength: 78,
    category: "kol-resonance",
    basis: "12位Trust Score>80的KOL在6小时内同时发布ETH看多观点，含3位历史命中率>65%，且链上ETH交易所净流出同步放大。",
    assets: ["ETH"],
    eventIds: ["evt-1"],
    kols: ["kol-1", "kol-2", "kol-4", "kol-6"],
    winRate: 71,
    avgReturn: 6.4,
    risk: "ETF资金流入不及预期可能引发回撤；注意3580-3650区间阻力。",
    ts: now - 1.2 * H,
    spark: spark(101, 24, 100, 0.03),
  },
  {
    id: "sig-2",
    title: "BTC链上资金持续净流入",
    direction: "bullish",
    confidence: 81,
    strength: 84,
    category: "onchain-flow",
    basis: "BTC现货ETF连续5日净流入累计+18.4亿美元，交易所BTC余额降至5年低点，长期持有者占比升至74%。",
    assets: ["BTC"],
    eventIds: ["evt-2"],
    kols: ["kol-3", "kol-5"],
    winRate: 66,
    avgReturn: 4.1,
    risk: "高位筹码集中，若跌破94000可能触发连环清算。",
    ts: now - 2.5 * H,
    spark: spark(102, 24, 100, 0.022),
  },
  {
    id: "sig-3",
    title: "Hyperliquid板块热度暴涨312%",
    direction: "bullish",
    confidence: 74,
    strength: 90,
    category: "sentiment-surge",
    basis: "HYPE相关中文推文24h增长312%，讨论人数突破4.2万，永续合约未平仓量创历史新高，资金费率转正且温和。",
    assets: ["HYPE"],
    eventIds: ["evt-4"],
    kols: ["kol-2", "kol-7"],
    winRate: 58,
    avgReturn: 12.8,
    risk: "热度驱动型行情波动剧烈，FOMO后常出现-20%回撤。",
    ts: now - 0.6 * H,
    spark: spark(103, 24, 100, 0.07),
  },
  {
    id: "sig-4",
    title: "交易所稳定币净流出增加",
    direction: "bearish",
    confidence: 63,
    strength: 55,
    category: "exchange-flow",
    basis: "USDT连续3日从交易所净流出4.2亿美元，购买力减弱，叠加Meme板块资金撤离迹象。",
    assets: ["USDT", "PEPE", "WIF"],
    eventIds: ["evt-3"],
    kols: ["kol-8"],
    winRate: 61,
    avgReturn: -3.2,
    risk: "若稳定币重回交易所则信号失效。",
    ts: now - 3.1 * H,
    spark: spark(104, 24, 100, 0.03),
  },
  {
    id: "sig-5",
    title: "鲸鱼持续建仓 RWA 板块",
    direction: "bullish",
    confidence: 69,
    strength: 72,
    category: "whale-accumulation",
    basis: "3个标记地址7日内累计买入ONDO 1840万美元、PENDLE 620万美元，且无明显出货痕迹，与RWA板块ETF预期形成共振。",
    assets: ["ONDO", "LINK"],
    eventIds: ["evt-5"],
    kols: ["kol-5", "kol-9"],
    winRate: 64,
    avgReturn: 7.9,
    risk: "RWA叙事持续性存疑，关注监管表态。",
    ts: now - 4.4 * H,
    spark: spark(105, 24, 100, 0.04),
  },
  {
    id: "sig-6",
    title: "BTC衍生品杠杆快速上升",
    direction: "neutral",
    confidence: 58,
    strength: 67,
    category: "derivative",
    basis: "BTC永续合约未平仓量24h+14%，资金费率0.011%/8h偏热，历史类似形态短期波动率中位数+38%。",
    assets: ["BTC"],
    eventIds: ["evt-2"],
    kols: ["kol-3"],
    winRate: 60,
    avgReturn: 1.2,
    risk: "高杠杆环境下双向波动放大，非方向性信号。",
    ts: now - 5.2 * H,
    spark: spark(106, 24, 100, 0.05),
  },
];

export const events: Event[] = [
  {
    id: "evt-1",
    title: "ETH现货ETF资金流入创近两月新高",
    summary:
      "ETH现货ETF单日净流入3.8亿美元，为过去60日最大单日流入。多家机构持仓数据显示增持迹象，中文KOL圈出现高密度看多共振。",
    importance: "critical",
    importanceScore: 92,
    sentiment: 78,
    direction: "bullish",
    sectors: ["ETH", "ETF", "DeFi"],
    assets: ["ETH"],
    ts: now - 3 * H,
    reach: 184000,
    velocity: 96,
    kolCount: 28,
    tweetCount: 1240,
    status: "developing",
    aiAnalysis: {
      oneLiner: "ETH现货ETF资金回暖叠加KOL共振，是本轮ETH相对强势的核心驱动。",
      background:
        "自8月起ETH现货ETF持续净流出，市场对ETH叙事信心不足。近一周资金面出现拐点，机构端增持与质押预期形成正反馈。",
      bullCase: "若流入延续3-5日，ETH有望突破3650阻力并向3800迈进；ETH/BTC汇率或止跌回升。",
      bearCase: "若BTC出现-5%级回撤，资金流入可能戛然而止，ETH补跌幅度通常更大。",
      outlook: "短期偏多，关注ETF流入连续性与3650-3700突破有效性。",
      risk: "ETF资金属短线资金，持续性弱于长期持有者。",
      watch: ["ETF日净流入", "ETH/BTC汇率", "交易所ETH余额", "质押率变化"],
    },
    timeline: [
      { ts: now - 6 * H, label: "T-6h", desc: "BlackRock IBIT 端出现大额申购迹象" },
      { ts: now - 4 * H, label: "T-4h", desc: "ETF净流入数据公布，+3.8亿美元" },
      { ts: now - 3 * H, label: "T-3h", desc: "中文KOL圈开始集中讨论，看多声量快速上升" },
      { ts: now - 1 * H, label: "T-1h", desc: "ETH突破3600，永续合约持仓同步上升" },
      { ts: now - 0.2 * H, label: "Now", desc: "情绪指数升至78，进入偏热区间" },
    ],
    outcome: { "1h": 0.8, "24h": 4.1, "7d": 6.2, "30d": 0, "90d": 0 },
    kols: ["kol-1", "kol-2", "kol-4", "kol-6"],
    relatedEvents: ["evt-2", "evt-5"],
    spark: spark(201, 32, 100, 0.03),
  },
  {
    id: "evt-2",
    title: "BTC突破96000，逼近历史高点",
    summary:
      "BTC在链上资金持续流入推动下突破96000美元，距前高仅3%。交易所BTC余额降至5年低点，长期持有者占比74%。",
    importance: "critical",
    importanceScore: 95,
    sentiment: 71,
    direction: "bullish",
    sectors: ["BTC", "ETF"],
    assets: ["BTC"],
    ts: now - 5 * H,
    reach: 312000,
    velocity: 88,
    kolCount: 41,
    tweetCount: 2870,
    status: "developing",
    aiAnalysis: {
      oneLiner: "筹码锁定+ETF资金流入是BTC冲击前高的核心动能。",
      background:
        "本轮BTC上行由现货驱动，杠杆水平温和。长期持有者占比创历史新高，供给端持续收紧。",
      bullCase: "站稳96000后有望挑战前高100000，突破后机构FOMO可能加速。",
      bearCase: "前高附近筹码抛压较大，首次冲击常伴随-4%~-6%回撤。",
      outlook: "中期看多，短期警惕前高假突破风险。",
      risk: "衍生品杠杆上升过快可能放大回调幅度。",
      watch: ["ETF净流入", "交易所BTC余额", "前高成交量分布", "资金费率"],
    },
    timeline: [
      { ts: now - 24 * H, label: "T-24h", desc: "ETF连续5日净流入累计+18.4亿美元" },
      { ts: now - 10 * H, label: "T-10h", desc: "交易所BTC余额降至5年低点" },
      { ts: now - 5 * H, label: "T-5h", desc: "BTC突破96000" },
      { ts: now - 2 * H, label: "T-2h", desc: "中文KOL集体看多，声量峰值" },
    ],
    outcome: { "1h": 0.4, "24h": 2.3, "7d": 5.1, "30d": 0, "90d": 0 },
    kols: ["kol-3", "kol-5", "kol-1"],
    relatedEvents: ["evt-1"],
    spark: spark(202, 32, 100, 0.025),
  },
  {
    id: "evt-3",
    title: "Pump.fun收入与TVL双降",
    summary:
      "Pump.fun日收入较高点下滑62%，TVL回落至8亿美元，Meme板块资金出现撤离迹象，社区讨论PumpSwap后续乏力。",
    importance: "medium",
    importanceScore: 64,
    sentiment: 32,
    direction: "bearish",
    sectors: ["Meme", "SOL"],
    assets: ["PUMP", "PEPE", "WIF"],
    ts: now - 8 * H,
    reach: 96000,
    velocity: 54,
    kolCount: 19,
    tweetCount: 760,
    status: "fading",
    aiAnalysis: {
      oneLiner: "Meme板块叙事降温，资金转向主流币与RWA。",
      background: "Pump.fun曾主导本轮Meme行情，但随着散户购买力衰减，新币成功率持续走低。",
      bullCase: "若PumpSwap机制升级或手续费调整，可能短期反弹。",
      bearCase: "资金撤离趋势确立，Meme板块通常先跌后横盘，反弹难创新高。",
      outlook: "偏空，Meme板块或进入震荡下行。",
      risk: "情绪反转可能在单日内发生，波动极大。",
      watch: ["Pump.fun日收入", "Meme板块资金占比", "SOL链上活跃度"],
    },
    timeline: [
      { ts: now - 48 * H, label: "T-48h", desc: "日收入首次跌破阶段均值" },
      { ts: now - 20 * H, label: "T-20h", desc: "TVL跌破10亿美元" },
      { ts: now - 8 * H, label: "T-8h", desc: "中文KOL开始提示Meme风险" },
    ],
    outcome: { "1h": -0.3, "24h": -3.1, "7d": -6.4, "30d": 0, "90d": 0 },
    kols: ["kol-8", "kol-7"],
    relatedEvents: [],
    spark: spark(203, 32, 100, 0.06),
  },
  {
    id: "evt-4",
    title: "Hyperliquid HYPE热度爆发",
    summary:
      "HYPE 24h上涨12.7%，永续合约未平仓量创历史新高，中文圈讨论热度暴涨312%，被视为本轮最强强势板块。",
    importance: "high",
    importanceScore: 81,
    sentiment: 84,
    direction: "bullish",
    sectors: ["DeFi", "AI"],
    assets: ["HYPE"],
    ts: now - 1.5 * H,
    reach: 142000,
    velocity: 99,
    kolCount: 23,
    tweetCount: 1890,
    status: "developing",
    aiAnalysis: {
      oneLiner: "Hyperliquid以永续合约龙头+代币回购机制成为本轮资金主线之一。",
      background: "Hyperliquid去中心化永续合约市占率持续提升，HYPE代币具备回购销毁机制。",
      bullCase: "未平仓量新高+回购机制形成正反馈，短期动能强劲。",
      bearCase: "热度驱动行情FOMO后常现-20%回撤，需警惕资金费率拐点。",
      outlook: "短期强势，中期需观察留存资金与市占率。",
      risk: "高波动，单日回撤可能超过15%。",
      watch: ["未平仓量", "资金费率", "市占率", "回购额度"],
    },
    timeline: [
      { ts: now - 12 * H, label: "T-12h", desc: "未平仓量创历史新高" },
      { ts: now - 4 * H, label: "T-4h", desc: "HYPE突破40美元" },
      { ts: now - 1.5 * H, label: "T-1.5h", desc: "中文圈讨论热度暴涨312%" },
    ],
    outcome: { "1h": 2.1, "24h": 12.7, "7d": 0, "30d": 0, "90d": 0 },
    kols: ["kol-2", "kol-7"],
    relatedEvents: [],
    spark: spark(204, 32, 100, 0.07),
  },
  {
    id: "evt-5",
    title: "RWA板块受机构与监管双重催化",
    summary:
      "Ondo、Chainlink等RWA标的集体走强，鲸鱼持续建仓，叠加美国监管层对代币化资产表态偏积极，板块情绪升至76。",
    importance: "high",
    importanceScore: 77,
    sentiment: 76,
    direction: "bullish",
    sectors: ["RWA", "DeFi", "Regulation"],
    assets: ["ONDO", "LINK"],
    ts: now - 9 * H,
    reach: 78000,
    velocity: 62,
    kolCount: 16,
    tweetCount: 540,
    status: "developing",
    aiAnalysis: {
      oneLiner: "RWA在机构资金与监管预期下成为本轮补涨主线。",
      background: "贝莱德代币化基金BUIDL规模持续增长，监管层对RWA态度相对友好。",
      bullCase: "若ETF与代币化政策持续推进，RWA板块仍有估值修复空间。",
      bearCase: "叙事偏长线，短期易受大盘回撤拖累。",
      outlook: "中性偏多，适合逢低配置。",
      risk: "监管表态反复可能打断叙事。",
      watch: ["BUIDL规模", "监管表态", "机构持仓变化"],
    },
    timeline: [
      { ts: now - 30 * H, label: "T-30h", desc: "BUIDL规模突破6亿美元" },
      { ts: now - 12 * H, label: "T-12h", desc: "监管层释放积极信号" },
      { ts: now - 9 * H, label: "T-9h", desc: "鲸鱼建仓数据被传播" },
    ],
    outcome: { "1h": 0.6, "24h": 4.8, "7d": 8.2, "30d": 0, "90d": 0 },
    kols: ["kol-5", "kol-9"],
    relatedEvents: ["evt-1"],
    spark: spark(205, 32, 100, 0.04),
  },
  {
    id: "evt-6",
    title: "SEC就稳定币监管发布新指引",
    summary:
      "SEC发布稳定币监管新指引草案，明确支付型稳定币的合规框架，USDT、USDC短期波动有限，市场解读偏正面。",
    importance: "high",
    importanceScore: 79,
    sentiment: 61,
    direction: "neutral",
    sectors: ["Stablecoin", "Regulation"],
    assets: ["USDT", "USDC"],
    ts: now - 14 * H,
    reach: 168000,
    velocity: 71,
    kolCount: 31,
    tweetCount: 1430,
    status: "peaked",
    aiAnalysis: {
      oneLiner: "稳定币监管落地消除不确定性，长期利好支付与RWA叙事。",
      background: "稳定币监管长期悬而未决，本次指引明确了合规路径。",
      bullCase: "合规框架落地利好头部稳定币与RWA板块。",
      bearCase: "短期对非合规项目构成压力。",
      outlook: "中长期偏多，短期影响有限。",
      risk: "指引仍为草案，最终规则存在变数。",
      watch: ["USDT/USDC市值", "监管立法进度", "RWA板块反应"],
    },
    timeline: [
      { ts: now - 16 * H, label: "T-16h", desc: "SEC预告将发布指引" },
      { ts: now - 14 * H, label: "T-14h", desc: "指引草案正式发布" },
      { ts: now - 6 * H, label: "T-6h", desc: "中文KOL解读密集发布" },
    ],
    outcome: { "1h": 0.1, "24h": 1.2, "7d": 2.4, "30d": 0, "90d": 0 },
    kols: ["kol-1", "kol-5", "kol-9"],
    relatedEvents: ["evt-5"],
    spark: spark(206, 32, 100, 0.02),
  },
];

export const kols: KOL[] = [
  {
    id: "kol-1",
    handle: "@CryptoPainter",
    name: "画线派Painter",
    avatar: "CP",
    bio: "专注技术分析与宏观周期，长期跟踪BTC/ETH结构。",
    followers: 412000,
    posts: 3820,
    avgEngagement: 8400,
    predictions: 184,
    hitRate: 68,
    bullRatio: 58,
    bearRatio: 42,
    trustScore: 88,
    influenceScore: 92,
    accuracyScore: 71,
    recentView: "ETH ETF资金回暖是结构性强信号，3650突破后看3800。",
    tags: ["技术分析", "宏观", "BTC"],
    spark: spark(301, 24, 100, 0.03),
    topCall: { asset: "ETH", direction: "bullish", return: 18.4, ts: now - 30 * D },
  },
  {
    id: "kol-2",
    handle: "@0xTodd",
    name: "Todd / Nothing",
    avatar: "TX",
    bio: "OnlyChain与永续合约赛道研究者，早期挖掘HYPE。",
    followers: 168000,
    posts: 2940,
    avgEngagement: 5200,
    predictions: 142,
    hitRate: 64,
    bullRatio: 63,
    bearRatio: 37,
    trustScore: 84,
    influenceScore: 79,
    accuracyScore: 66,
    recentView: "Hyperliquid的回购机制是本轮最强代币经济模型。",
    tags: ["DeFi", "永续合约", "Alpha"],
    spark: spark(302, 24, 100, 0.05),
    topCall: { asset: "HYPE", direction: "bullish", return: 124, ts: now - 60 * D },
  },
  {
    id: "kol-3",
    handle: "@BTC_Macro",
    name: "BTC宏观观察",
    avatar: "BM",
    bio: "链上数据与宏观流动性分析，专注BTC周期。",
    followers: 286000,
    posts: 2110,
    avgEngagement: 6800,
    predictions: 98,
    hitRate: 62,
    bullRatio: 55,
    bearRatio: 45,
    trustScore: 86,
    influenceScore: 85,
    accuracyScore: 64,
    recentView: "交易所BTC余额5年低点，现货ETF持续流入，前高可期。",
    tags: ["链上", "宏观", "BTC"],
    spark: spark(303, 24, 100, 0.025),
    topCall: { asset: "BTC", direction: "bullish", return: 9.2, ts: now - 14 * D },
  },
  {
    id: "kol-4",
    handle: "@DegenElf",
    name: "精灵Degen",
    avatar: "DE",
    bio: "Meme与高波动赛道交易员，胜率波动较大。",
    followers: 98000,
    posts: 5210,
    avgEngagement: 4100,
    predictions: 268,
    hitRate: 51,
    bullRatio: 74,
    bearRatio: 26,
    trustScore: 71,
    influenceScore: 74,
    accuracyScore: 52,
    recentView: "Meme板块资金撤离，建议降仓等待新叙事。",
    tags: ["Meme", "交易", "高波动"],
    spark: spark(304, 24, 100, 0.08),
    topCall: { asset: "WIF", direction: "bullish", return: 240, ts: now - 90 * D },
  },
  {
    id: "kol-5",
    handle: "@RWA_Arthur",
    name: "Arthur / RWA研究",
    avatar: "AR",
    bio: "RWA与代币化资产早期研究者，机构视角。",
    followers: 76000,
    posts: 1420,
    avgEngagement: 3100,
    predictions: 76,
    hitRate: 67,
    bullRatio: 61,
    bearRatio: 39,
    trustScore: 83,
    influenceScore: 68,
    accuracyScore: 68,
    recentView: "BUIDL规模持续增长，Ondo/LINK是RWA核心配置。",
    tags: ["RWA", "机构", "DeFi"],
    spark: spark(305, 24, 100, 0.04),
    topCall: { asset: "ONDO", direction: "bullish", return: 34, ts: now - 45 * D },
  },
  {
    id: "kol-6",
    handle: "@ETHMaxiLin",
    name: "Lin / ETH多头",
    avatar: "EL",
    bio: "ETH生态长期持有者，质押与L2研究者。",
    followers: 134000,
    posts: 1980,
    avgEngagement: 4600,
    predictions: 112,
    hitRate: 59,
    bullRatio: 81,
    bearRatio: 19,
    trustScore: 78,
    influenceScore: 72,
    accuracyScore: 60,
    recentView: "ETF资金回暖+质押预期，ETH汇率底已现。",
    tags: ["ETH", "L2", "质押"],
    spark: spark(306, 24, 100, 0.035),
    topCall: { asset: "ETH", direction: "bullish", return: 22, ts: now - 20 * D },
  },
  {
    id: "kol-7",
    handle: "@DerivativesQ",
    name: "Q / 衍生品观察",
    avatar: "DQ",
    bio: "永续合约、资金费率与清算地图分析师。",
    followers: 102000,
    posts: 2640,
    avgEngagement: 3800,
    predictions: 156,
    hitRate: 58,
    bullRatio: 52,
    bearRatio: 48,
    trustScore: 80,
    influenceScore: 71,
    accuracyScore: 60,
    recentView: "HYPE未平仓量新高但费率温和，动能未耗尽。",
    tags: ["衍生品", "永续合约", "数据"],
    spark: spark(307, 24, 100, 0.06),
    topCall: { asset: "HYPE", direction: "bullish", return: 41, ts: now - 7 * D },
  },
  {
    id: "kol-8",
    handle: "@FlowWatcher",
    name: "资金流观察",
    avatar: "FW",
    bio: "交易所资金流与稳定币监控，偏空头视角平衡。",
    followers: 88000,
    posts: 1760,
    avgEngagement: 2900,
    predictions: 134,
    hitRate: 60,
    bullRatio: 38,
    bearRatio: 62,
    trustScore: 82,
    influenceScore: 66,
    accuracyScore: 61,
    recentView: "USDT连续净流出，购买力减弱，Meme首当其冲。",
    tags: ["资金流", "稳定币", "风控"],
    spark: spark(308, 24, 100, 0.03),
    topCall: { asset: "PEPE", direction: "bearish", return: -18, ts: now - 12 * D },
  },
  {
    id: "kol-9",
    handle: "@RegWatcher",
    name: "监管观察站",
    avatar: "RW",
    bio: "全球监管动态跟踪，政策解读。",
    followers: 64000,
    posts: 980,
    avgEngagement: 2100,
    predictions: 64,
    hitRate: 63,
    bullRatio: 50,
    bearRatio: 50,
    trustScore: 85,
    influenceScore: 61,
    accuracyScore: 65,
    recentView: "稳定币指引落地，RWA与合规稳定币长期受益。",
    tags: ["监管", "稳定币", "RWA"],
    spark: spark(309, 24, 100, 0.02),
    topCall: { asset: "LINK", direction: "bullish", return: 11, ts: now - 18 * D },
  },
];

export const sentiments: Sentiment[] = [
  { sector: "all", label: "全市场", now: 68, "24h": 62, "7d": 58, "30d": 51, trend: spark(401, 30, 60, 0.05) },
  { sector: "BTC", label: "BTC", now: 71, "24h": 66, "7d": 60, "30d": 55, trend: spark(402, 30, 64, 0.04) },
  { sector: "ETH", label: "ETH", now: 78, "24h": 64, "7d": 55, "30d": 48, trend: spark(403, 30, 60, 0.06) },
  { sector: "SOL", label: "SOL", now: 54, "24h": 58, "7d": 61, "30d": 60, trend: spark(404, 30, 58, 0.05) },
  { sector: "Meme", label: "Meme", now: 32, "24h": 41, "7d": 52, "30d": 64, trend: spark(405, 30, 55, 0.08) },
  { sector: "AI", label: "AI", now: 66, "24h": 60, "7d": 57, "30d": 50, trend: spark(406, 30, 56, 0.05) },
  { sector: "Layer2", label: "Layer2", now: 49, "24h": 47, "7d": 50, "30d": 53, trend: spark(407, 30, 50, 0.04) },
  { sector: "RWA", label: "RWA", now: 76, "24h": 70, "7d": 64, "30d": 52, trend: spark(408, 30, 58, 0.05) },
  { sector: "DeFi", label: "DeFi", now: 63, "24h": 58, "7d": 55, "30d": 49, trend: spark(409, 30, 54, 0.05) },
  { sector: "ETF", label: "ETF", now: 73, "24h": 65, "7d": 59, "30d": 54, trend: spark(410, 30, 58, 0.04) },
  { sector: "Regulation", label: "监管", now: 61, "24h": 58, "7d": 56, "30d": 50, trend: spark(411, 30, 55, 0.03) },
];

export const projects: Project[] = [
  { id: "p-1", name: "Hyperliquid", symbol: "HYPE", sector: "DeFi", heat: 96, heatChange: 312, mentions: 1890, kolMentions: 23, price: 41.6, change24h: 12.7, spark: spark(501, 24, 100, 0.07) },
  { id: "p-2", name: "Ethereum", symbol: "ETH", sector: "ETH", heat: 88, heatChange: 42, mentions: 1240, kolMentions: 28, price: 3624, change24h: 4.12, spark: spark(502, 24, 100, 0.03) },
  { id: "p-3", name: "Bitcoin", symbol: "BTC", sector: "BTC", heat: 85, heatChange: 28, mentions: 2870, kolMentions: 41, price: 96840, change24h: 2.34, spark: spark(503, 24, 100, 0.025) },
  { id: "p-4", name: "Ondo Finance", symbol: "ONDO", sector: "RWA", heat: 74, heatChange: 58, mentions: 540, kolMentions: 16, price: 1.94, change24h: 8.9, spark: spark(504, 24, 100, 0.05) },
  { id: "p-5", name: "Chainlink", symbol: "LINK", sector: "RWA", heat: 69, heatChange: 31, mentions: 610, kolMentions: 14, price: 24.1, change24h: 3.3, spark: spark(505, 24, 100, 0.035) },
  { id: "p-6", name: "Solana", symbol: "SOL", sector: "SOL", heat: 64, heatChange: -8, mentions: 760, kolMentions: 19, price: 218.4, change24h: -1.82, spark: spark(506, 24, 100, 0.04) },
  { id: "p-7", name: "Aave", symbol: "AAVE", sector: "DeFi", heat: 58, heatChange: 22, mentions: 320, kolMentions: 9, price: 348, change24h: 5.6, spark: spark(507, 24, 100, 0.04) },
  { id: "p-8", name: "Pump.fun", symbol: "PUMP", sector: "Meme", heat: 47, heatChange: -36, mentions: 420, kolMentions: 11, price: 0.082, change24h: -6.4, spark: spark(508, 24, 100, 0.07) },
  { id: "p-9", name: "Pepe", symbol: "PEPE", sector: "Meme", heat: 41, heatChange: -28, mentions: 380, kolMentions: 8, price: 0.0000218, change24h: -4.6, spark: spark(509, 24, 100, 0.08) },
  { id: "p-10", name: "dogwifhat", symbol: "WIF", sector: "Meme", heat: 38, heatChange: -19, mentions: 290, kolMentions: 7, price: 2.74, change24h: 9.1, spark: spark(510, 24, 100, 0.09) },
];

export const flows: FlowRecord[] = [
  { asset: "BTC", netFlow: 1.84e9, exchangeInflow: 0.62e9, exchangeOutflow: 2.46e9, whaleNet: 720e6, stablecoinSupply: 142e9, change: 2.3 },
  { asset: "ETH", netFlow: 0.92e9, exchangeInflow: 0.41e9, exchangeOutflow: 1.33e9, whaleNet: 380e6, stablecoinSupply: 0, change: 4.1 },
  { asset: "SOL", netFlow: -0.12e9, exchangeInflow: 0.38e9, exchangeOutflow: 0.26e9, whaleNet: -90e6, stablecoinSupply: 0, change: -1.8 },
  { asset: "USDT", netFlow: -0.42e9, exchangeInflow: 0.18e9, exchangeOutflow: 0.60e9, whaleNet: 0, stablecoinSupply: 142e9, change: -0.3 },
  { asset: "HYPE", netFlow: 0.21e9, exchangeInflow: 0.08e9, exchangeOutflow: 0.29e9, whaleNet: 140e6, stablecoinSupply: 0, change: 12.7 },
];

export const propagationNodes: PropagationNode[] = [
  { id: "n1", label: "CoinDesk", group: "origin", value: 60, lang: "en" },
  { id: "n2", label: "画线派Painter", group: "amplifier", value: 95, lang: "zh" },
  { id: "n3", label: "BTC宏观观察", group: "amplifier", value: 80, lang: "zh" },
  { id: "n4", label: "0xTodd", group: "spread", value: 55, lang: "zh" },
  { id: "n5", label: "ETH多头Lin", group: "spread", value: 48, lang: "zh" },
  { id: "n6", label: "WuBlockchain", group: "amplifier", value: 70, lang: "zh" },
  { id: "n7", label: "BlockBeats", group: "spread", value: 64, lang: "zh" },
  { id: "n8", label: "Pentosh1", group: "global", value: 50, lang: "en" },
  { id: "n9", label: "社区散户群A", group: "spread", value: 30, lang: "zh" },
  { id: "n10", label: "社区散户群B", group: "spread", value: 26, lang: "zh" },
  { id: "n11", label: "监管观察站", group: "spread", value: 40, lang: "zh" },
  { id: "n12", label: "Crypto中文化", group: "global", value: 38, lang: "zh" },
];

export const propagationLinks: PropagationLink[] = [
  { source: "n1", target: "n2", value: 8 },
  { source: "n1", target: "n6", value: 6 },
  { source: "n6", target: "n3", value: 7 },
  { source: "n6", target: "n7", value: 6 },
  { source: "n2", target: "n4", value: 5 },
  { source: "n2", target: "n5", value: 5 },
  { source: "n3", target: "n5", value: 4 },
  { source: "n7", target: "n9", value: 4 },
  { source: "n7", target: "n10", value: 3 },
  { source: "n3", target: "n11", value: 3 },
  { source: "n1", target: "n8", value: 5 },
  { source: "n8", target: "n12", value: 4 },
  { source: "n12", target: "n9", value: 3 },
  { source: "n4", target: "n10", value: 3 },
];

export function getEvent(id: string): Event | undefined {
  return events.find((e) => e.id === id);
}
export function getKol(id: string): KOL | undefined {
  return kols.find((k) => k.id === id);
}
